name: CI

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            # 1) checkout your code
            - uses: actions/checkout@v4

            # 2) set up Python
            - uses: actions/setup-python@v4
              with:
                python-version: '3.8'

            # 3) Install dependencies
            - name: Install Dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            # 4) Prepare (create) test database schema
            - name: Create test DB
              run: python create_tables.py

            # 5) Run Tests
            - name: Run pytest
              run: pytest -q